### ISSUE TITLE
Icon and name is a copy of Photopea

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.vikdevelop.photopea_app#10]
We are tracking a bunch of applications with trademark violations or icons/names that copy brand names of other applications.

Since this is an unofficial wrapper and not affiliated to the [Photopea project](https://www.photopea.com/), you cannot use someone else's application name and icon for your application.

Please change the name and icon to be distinct. A good example is an unofficial whatsapp client on Flathub called "Youp for Whatsapp". So you can name it `$something for Photopea`.

But the icon needs to be completely distinct.

I think two months from now is a reasonable time period to come to a solution here.

See https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#no-trademark-violations

**Comment by vikdevelop** [comment]
Hello,
how about using the name "Photocrea", and the icon below?

<img src=https://github.com/flathub/com.github.vikdevelop.photopea_app/assets/83600218/c7f62f3b-dc37-4945-874e-46fc095d09c6 width="128">

**Comment by bbhtt** [comment]
Seems fine as long as it doesn't violate any other known trademarks/brands.


A cursory search for Photocrea doesn't bring up anything related or of concern right now. I haven't checked the icon.

**Comment by vikdevelop** [comment]
This icon open source and it is licensed under the GPL v3 license and it is from this website: https://iconduck.com/icons/310900/gnome-photos

So, I will rename the app to "Photocrea" and replace the current icon with this icon.

**Comment by vikdevelop** [comment]
Everything is more or less ready. All that's left is to rename the application ID.  What will happen to this repository if it is called com.github.vikdevelop.photopea_app instead of com.github.vikdevelop.photocrea?

**Comment by bbhtt** [comment]
You don't need to change the ID, changing the user visible parts only is fine.

**Comment by vikdevelop** [comment]
I merged the build with the new icon and name, see https://github.com/flathub/com.github.vikdevelop.photopea_app/pull/11
