### ISSUE TITLE
Photopea isn't open source

### ISSUE THREAD

**Issue by jimboolio** [flathub/com.github.vikdevelop.photopea_app#2]
https://github.com/photopea/photopea/issues/1604

I feel like listing the flatpak as open source can cause the users believing Photopea (website) is open source. They might go to the Photopea (website) repo on github which exists, but doesn't contain any code or license. It is very likely they might assume that the Photopea (Flatpak) license actually covers Photopea (website) too. It is great to see open source software, but in this case there's very real risk for confusion and even disappointment if Photopea (website) happens to go down and they would realize that their tool doesn't exist.

**Comment by vikdevelop** [comment]
Thank you of your reply. I agree, that photopea webapp is not open-source. My webview wrapper is under MIT license. On Flathub page  is listed MIT licensem because Flathub lists a license of desktop app, not a license of webapp.

**Comment by vikdevelop** [comment]
> But is the photopea app bundled inside the flatpak? If so, AFAIK; the license cannot be MIT, but it is MIT + proprietary, i.e. it is proprietary.
> 
> It's kinda misleading I'd say, and other packages like IntelliJ Ultimate are also listed as proprietary with the hint that there is a wrapper: https://flathub.org/apps/com.jetbrains.IntelliJ-IDEA-Ultimate

@rugk When I wanted to publish this app on Flathub in September 2021, they told me that on the flathub page it must state the license of the application (electron wrapper), which is the MIT license, not the license of the web application.

**Comment by jimboolio** [comment]
In this case most of the functionality regarding image editing is in the webpage. Packaging is the delivery method of in this case a web application. And while I really appreciate having open source packaging, it is still one - very important one, component of an application. Many proprietrary applications are based on open source code and that doesn’t make the end result open. As a user what matters to me is the most restrictive licence of a complete application experience, since that’s the most likely cause if ever am I forced to quit using the application due to licencing restrictions.

I really appreciate that this application exists but I’m somewhat worried that this could have potential for misunderstanding among some users who assume they’re going to find Photopea (the website) code somewhere
